#!/bin/sh
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)"

check_run() {
  echo "$changed_files" | grep --quiet "$1" && echo " * changes detected in $1: running $2" && eval "$2"
}

# Git
check_run ".gitmodules" "git submodule update --init"

# Node/Bower
check_run "package.json" "npm install"
check_run "bower.json" "bower install"

# PHP
check_run "composer.json" "composer install"

# Ruby/Rails
check_run "Gemfile" "bundle install --path='vendor/bundle'"
check_run "db/*" "bundle exec rake db:migrate db:seed"
